import { NextPage } from 'next'
import Head from 'next/head'

const HomePage: NextPage = () => {
  return (
    <div className='container'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by Nonextplate' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='main'>
        <h1 className='title'>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>

        <p className='description'>
          <a href='https://github.com/kalwabed/nonextplate'>Nonextplate</a> is a boilerplate for creating Next.js
          applications.
        </p>
      </main>

      <style jsx>
        {`
          .container {
            padding: 0 2rem;
          }

          .main {
            min-height: 100vh;
            padding: 4rem 0;
            flex: 1;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
          }

          a {
            color: #0070f3;
            text-decoration: none;
          }

          a:hover,
          a:focus,
          a:active {
            text-decoration: underline;
          }

          .title {
            margin: 0;
            line-height: 1.15;
            font-size: 4rem;
          }

          .title,
          .description {
            text-align: center;
          }

          .description {
            margin: 4rem 0;
            line-height: 1.5;
            font-size: 1.5rem;
          }

          .code {
            background: #fafafa;
            border-radius: 5px;
            padding: 0.75rem;
            font-size: 1.1rem;
            font-family: Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono, Bitstream Vera Sans Mono,
              Courier New, monospace;
          }

          @media (prefers-color-scheme: dark) {
            .code {
              background: #111;
            }
          }
        `}
      </style>
    </div>
  )
}

export default HomePage
